services:
  coturn:
    image: coturn/coturn:latest
    container_name: coturn-server
    restart: always
    ports:
      - '3478:3478/udp'
      - '3478:3478/tcp'
      - '5349:5349/udp'
      - '5349:5349/tcp'
      - "49152-49200:49152-49200/udp"
      - "49152-49200:49152-49200/tcp"
    volumes:
      - /etc/letsencrypt/live/pinoco.shop/fullchain.pem:/etc/letsencrypt/live/pinoco.shop/fullchain.pem
      - /etc/letsencrypt/live/pinoco.shop/privkey.pem:/etc/letsencrypt/live/pinoco.shop/privkey.pem
      - ./turnserver.conf:/etc/turnserver.conf:ro
    command: turnserver -c /etc/turnserver.conf --verbose