services:
  signaling-server:
    image: todayisfirst/signaling-server:latest
    container_name: signaling-server
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production
      - SIGNALING_SERVER_PORT=8080
      - ORIGIN=*
      - SSL_CERT_PATH=/etc/letsencrypt/live/pinoco.shop/fullchain.pem
      - SSL_KEY_PATH=/etc/letsencrypt/live/pinoco.shop/privkey.pem
    volumes:
      # SSL 인증서 마운트
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: always
